name: Autodoc

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  goreadme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update readme according to Go doc
      uses: posener/goreadme@v1
      with:
        email: ${{ secrets.EMAIL }}
        recursive: true
        badge-golangci: true
        badge-godoc: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
