name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  golangci:
    name: lint
    strategy:
        matrix:
          lint-folders: [server, client]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install GL
        run: sudo apt-get install libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxxf86vm-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          skip-go-installation: true
          args: --timeout=600
          working-directory: ${{ matrix.lint-folders }}
