name: Release
on:
  release:
    types:
      - created
      - edited
  workflow_dispatch:

jobs:
  build:
    name: Building apps
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        app: [server, client]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install GL
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxxf86vm-dev

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build app (Linux & MacOS)
        if: matrix.os != 'windows-latest'
        run: go build -o bin/${{ matrix.app }}-${{ matrix.os }} SSoC/cmd/${{ matrix.app }}

      - name: Build app (Windows)
        if: matrix.os == 'windows-latest'
        run: go build -o bin/${{ matrix.app }}-${{ matrix.os }}.exe SSoC/cmd/${{ matrix.app }}

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries-${{ matrix.os }}
          path: bin/

  upload:
    name: Upload release artifacts
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artefacts
        uses: actions/download-artifact@v1
        with:
          name: binaries-${{ matrix.os }}
          path: bin/

      - name: Create release archive
        run: |
          mkdir release
          zip -r release/ssoc-${{ matrix.os }}.zip files config.yaml
          zip -uj release/ssoc-${{ matrix.os }}.zip bin/*

      - name: Upload release assets
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './release/*'
