name: Multiplatform test

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Install GL
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Client test
      run: |
        cd client
        go test ./...

    - name: Server test
      run: |
        cd server
        go test ./...
